version: '3.8'

services:
  app:
    image: my-spring-boot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_samsung
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=W14i05l77!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: W14i05l77!
      MYSQL_DATABASE: db_samsung
      MYSQL_USER: admin
      MYSQL_PASSWORD: W14i05l77!
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql      
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
