version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: W14i05l77!
      MYSQL_DATABASE: db_samsung
      MYSQL_USER: admin
      MYSQL_PASSWORD: W14i05l77!      
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3306:3306"   

  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network     
    depends_on:
      - db       

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production   
    depends_on:
      - backend          
 
networks:
  app-network:
    driver: bridge